## WORKS on github; not on act (something about 'git')

name: 320 simple file save 

on:
  workflow_dispatch:

# token needs
permissions:
  contents:  write

#A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

#   Steps represent a sequence of tasks that will be executed as part of the job
    steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "hello  $GITHUB_ACTION_PATH" >> hello.txt
        shell: bash
        env:
          GITHUB_ACTION_PATH:  ${{ github.action_path }}

#       # Run goodbye.sh
#      - name:  goodbye.sh
#        run:  ./goodbye.sh
#        shell: bash

      # save to file
      - name: save
        run: echo "hello" >> hello.txt

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: push
        run: |
          date >> hello.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "commit by github actions"
          git push
        shell: bash
