name: 002_render_README.Rmd

run-name:  run_name is render

on:  [workflow_dispatch]

permissions:
  contents:  write

jobs:
  quarto:
    runs-on: ubuntu-latest
    container:
      image:  rocker/r-ver:latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2 
        with:
          packages: |
            any::readr
            any::tidyr
            any::dplyr
            any::lubridate
            any::stringr
            any::R.utils
            any::quarto
            any::jsonlite

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

#        # Install R dependencies
#        run: |
#          Rscript -e 'install.packages(
#          c("dplyr", "jsonlite", "quarto", "diffdf", "rmarkdown", "safetyData",
#          "tibble", "stringr", "haven"),
#          repos = "https://packagemanager.posit.co/cran/__linux__/noble/latest")'


       - name: Render Quarto Project
         uses: quarto-dev/quarto-actions/render@v2
         with:
           to: html # If set, it will be equivalent to `quarto render --to html`

      - name:  install knitr
        run:  Rscript -e 'install.packages("knitr")'

      - name:  install rmarkdown
        run:  Rscript -e 'install.packages("rmarkdown")'

      - name: Render Quarto document
        run: |
          quarto render README.Rmd  --to gfm --output README.md
	  quarto render README.Rmd 

#quarto render 280_emacs_notes.qmd --to gfm --output 280_emacs_notes.md
#quarto render 250_quarto_knitr_SCSS_NOTES.qmd --to gfm --output 250_quarto_knitr_SCSS_NOTES.md

    # Commit and push changes to README.md
      - name: Commit README.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md from README.Rmd"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


