# WORKS
name:  simple_push

run-name: simple_push is run-name

on:
  workflow_dispatch:
    branches: main
  push:
    branches: [main, special_br] 

jobs:
  task1:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: echo
        run:  echo "This is workflow_dispatch"

       
  print_something:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run script
        run: Rscript -e 'source("R/01_first.R")'

