name: 100_built_in

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
     - name:  built-in
       run: |
         echo "100_buit_in"
         echo "SHA = ${{ env.GITHUB_SHA }}"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: SHA_with_var
        run: |
         echo "VAR=$(echo $GITHUB_SHA)" >> "$GITHUB_ENV"

  job3:
    runs-on: ubuntu-latest
    steps:
      -name: print
       run: |
         echo $VAR