name: 100_built_in

on:
  workflow_dispatch:

run-name:  echo "number = $GITHUB_RUN_ATTEMPT"

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
     - name:  built-in
       run: |
         echo "100_buit_in"
         echo "SHA = ${{ env.GITHUB_SHA }}"

     - name:  print
       run: |
         echo "Run id = $GITHUB_RUN_ID"
         echo "Run attempt = $GITHUB_RUN_ATTEMPT"
         echo "Run number = $GITHUB_RUN_NUMBER"
         echo "ACTOR = $GITHUB_ACTOR"
         echo "OS = $RUNNER_OS"
         echo "EVENT = $GITHUB_EVENT_NAME"
