#  Works on ACT
name:  100_simple_env_variables

run-name: simple_source is run-name

on:
  workflow_dispatch:
env:
  NAME: "top"

jobs:
  task1:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: echo1
        run: |
          echo 'This is ${{ env.NAME }}' >> '$GITHUB_OUTPUT'

      - name: echo2
        run: |
          echo "This is task1 and workflow_dispatch"
          echo 'This is task1 ${{ env.NAME }}'
        env:
          NAME: "task1"
          run: echo 'This is task1 ${{ env.NAME }}'




  task2:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    env:
      NAME: "task2"
    steps:
      - name: echo2
        run:  echo 'This is ${{ env.NAME }}'
