name: 130_git

on:
  # pull_request:
  push:
  # workflow_dispatch:

run-name:  ${{ github.event_name }}, branch is ${{ github.headref || github.ref_name }}, ${{ github.run_number }}, @${{ github.actor }}

jobs:
  job-1:
    name: JOB1
    runs-on: ubuntu-latest
    if: ${{ 2 > 4 }}
    steps:
      - name: Print environment variables
        run: env

      - name: Print events.json
        run: cat "$GITHUB_EVENT_PATH"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

  job-3:
    name:  JOB-3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install git
        run: |
          apt-get update
          apt-get install -y git


      - name: ls
        run:  |
          echo "RUNNING:  job-3"
          #ls -la *.yml

      - name:  git
        run: git status
        working-directory:  ${{ github.workspace }}


      - name:  diff
        run:  |
          echo "RUNNING git diff"
          git diff

      - name:  diff last
          echo "RUNNING git diff ;  1= change"
          git diff  --exit-code | $?


# NEEDS git installed !
      - name: git ls-files
        if: ${{ 2 > 4 }}
        run:  git ls-files | grep 'yml'


#      - name: bash
#        run: |
#          # If there are any unstaged or untracked files in 'dist/', then the action wasn't packaged properly
#          if git diff --name-only | grep '^dist/' || git ls-files --other --exclude-standard | grep '^dist/'; then
#            echo "You didn't package the action properly before pushing to remote." \
#            echo "Always run 'yarn all' before staging a commit."
#            echo "Below are the modified files in 'dist/' after running 'yarn && rm -rf dist/ && yarn all':"
#            git diff --name-only | grep '^dist/'
#            git ls-files --other --exclude-standard | grep '^dist/'
#            exit 1
#          fi
