name: 130_git

##  RUN on github, not act
##  compare 2 commits, diff?

run-name: Hello  Try ${{ github.run_number }}, @${{ github.actor }}

on:
  push:
  # workflow_dispatch:


jobs:
  check_git:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Git is installed and show version
        run: |
          echo "Running 'git --version' directly:"
          git --version
          echo "Git is indeed installed and available."

      - name: ls
        run:  |
          echo "RUNNING:  job-3"
          ls -la *.yml

      - name:  git
        run: git status
        working-directory:  ${{ github.workspace }}


      - name:  diff
        run:  |
          echo "RUNNING git diff"
          git diff

      - name:  diff last
        run: |
          echo "RUNNING git diff ;  1= change"
          git diff  --exit-code | $?


# NEEDS git installed !
      - name: git ls-files
        if: ${{ 2 > 4 }}
        run:  git ls-files | grep 'yml'


#      - name: bash
#        run: |
#          # If there are any unstaged or untracked files in 'dist/', then the action wasn't packaged properly
#          if git diff --name-only | grep '^dist/' || git ls-files --other --exclude-standard | grep '^dist/'; then
#            echo "You didn't package the action properly before pushing to remote." \
#            echo "Always run 'yarn all' before staging a commit."
#            echo "Below are the modified files in 'dist/' after running 'yarn && rm -rf dist/ && yarn all':"
#            git diff --name-only | grep '^dist/'
#            git ls-files --other --exclude-standard | grep '^dist/'
#            exit 1
#          fi
