name: Check Git Version

on:
  push:


jobs:
  check_git:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Git is installed and show version
        run: |
          echo "Running 'git --version' directly:"
          git --version
          echo "Git is indeed installed and available."