name: 132_git_diff.yml

##  RUN on github, not act
##  compare 2 commits, diff?

run-name: 132_git_diff ${{ github.run_number }}, @${{ github.actor }}

on:
  #push:
  workflow_dispatch:


jobs:
  check_git:
    runs-on: ubuntu-latest

    steps:

      - name: Install Git (REQUIRED FOR THIS SPECIFIC DOCKER IMAGE)
        if: ${{ env.ACT }}  # install if act
        run: |
          echo "On act... installing git, suppress output"
          apt-get update > /dev/null 2>&1 # Update package lists
          apt-get install -y git > /dev/null 2>&1 # Install git

      - name: Verify Git is installed and show version
        run: |
          echo "Running 'git --version' directly:"
          git --version
          echo "Git is indeed installed and available."

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
# entire history

      - name: ls
        run:  |
          echo "RUNNING:  ls -la **/*.yml <SNIP>"
          #ls -la **/*.yml

      - name:  git
        run:
          echo "git status"
          git status
        #working-directory:  ${{ github.workspace }}


      - name:  diff (getting stuck in this step?)
        if: ${{ 2 > 4 }}
        run:  |
          echo "RUNNING git diff"
          git diff HEAD

      - name:  diff HEAD~
        run: |
          echo "RUNNING git diff HEAD~ exit-code;  1= change"
          git diff HEAD~ --exit-code | echo $?

      - name:  diff HEAD
        run: |
          echo "RUNNING git diff HEAD exit-code;  1= change"
          git diff HEAD --exit-code | echo $?

      - name:  diff HEAD
        run: |
          echo "RUNNING git diff HEAD HEAD~ exit-code;  1= change"
          git diff HEAD HEAD~ --exit-code | echo $?

      - name: Display diff for the current push
        if: ${{ github.event_name == 'push' }} # Only runs for push events
        run: |
          echo "Comparing from ${{ github.event.before }} to ${{ github.sha }}"
          echo "--- Git Diff (all changes in this push) ---"
          git diff ${{ github.event.before }} ${{ github.sha }}

          echo "--- Files changed (names only) ---"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

          # You can also count the number of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)
          echo "Number of changed files in this push: $CHANGED_FILES"

