name:  201 simple-R dependencies

run-name: 201 dependencies

on:
  workflow_dispatch:
#  pull_request:

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        if: ${{ !env.ACT }}  # do not on act
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'
          use-public-rspm: true

      - name: Install packages
        if: ${{ !env.ACT }}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: hard

      - name: Run script
        run: Rscript -e 'source("R/01_first.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
