## works, but can not isntall git
name:  205 rocker 

## USE  rocker,  but no git?, otherwise works
run-name: 205 dependencies

on:
  #workflow_dispatch:
  push:
# pull_request:

permissions:  read-all

jobs:
  import-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: rocker/r-ver:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install git
        run: |
         apt-get update
         apt-get install -y git

      - name:  git
        run:  |
          git status
        working-directory:  ${{ github.workspace }}

      - name:  install binary pak - WoRKS!
        run:  Rscript -e 'install.packages("pak",
           repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s",
           .Platform$pkgType, R.Version()$os, R.Version()$arch))'

      - name:  install diffdf binary  -- works
        run:  Rscript -e 'pak::pkg_install("diffdf")'  # default is binary


## ------------------------  git fails 

#      - name:  install git (sudo requires no passwd)
#        run:  |
#          sudo apt update
#          sudo apt-get install git -y

#      - name: Extra deps
#        if: runner.os == 'Linux'
#        run: |
#          sudo apt-get install -y autoconf automake git global libgit2-dev libglpk-dev

#      - name: Set up R
#        if: ${{ !env.ACT }}  # do not on act
#        uses: r-lib/actions/setup-r@v2
#        with/:
#          r-version: 'latest'
#          use-public-rspm: true
#
#      - name: Install packages
#        if: ${{ !env.ACT }}
#        uses: r-lib/actions/setup-r-dependencies@v2
#        with:
#          dependencies: hardk

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
