# WORKS !
name:  210 Rsimple R script

run-name: runs simple R script

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  rocker/r-ver:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run script
        run: Rscript -e 'source("R/01_first.R")'
