# render:  fails on act
name: 220 render QC ✅

on:
  workflow_dispatch:

# token needs
permissions:
  contents:  write


jobs:
  qc-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image:  rocker/r-ver:latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name:  quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr", "jsonlite", "quarto", "diffdf", "rmarkdown", "safetyData", "tibble", "stringr", "haven"), repos = "https://packagemanager.posit.co/cran/__linux__/noble/latest")'

      - name: Render Quarto document
        run: |
          quarto render README.Rmd  --to gfm --output README.md

      - name: Run QC script
        run: R -e 'quarto::quarto_render("README.Rmd")'

#      - name: Upload report artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: qcReport.html
#          path: qcReport.html

#      - name: PR comment with file
#        uses: thollander/actions-comment-pull-request@v3
#        with:
#          file-path: qc.Rmd


