name:  308_simple_gfm

run-name: 308_simple_gfm

on:
  workflow_dispatch:
  pull_request:


jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Adding markdown
        run: |
          echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY
          echo "   _(event **${{ github.event_name }}** / attempt **${{ github.run_attempt }}**)_"

      - name: check outputs
        if ${{ 2 > 3 }}
        run: |
          echo "id : ${{ steps.PR_comment.outputs.id }}"
          echo "body : ${{ steps.PR_comment.outputs.body }}"
          echo "html-url : ${{ steps.PR_comment.outputs.html-url }}"
          echo ":heavy-check_mark:"


      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        if: ${{ 2 > 3}}
        id: PR_comment
        with:
          message: |
             I am a bot.
             :heavy_check_mark:
             _(event **${{ github.event_name }}** / attempt **${{ github.run_attempt }}**)_
