name:  308_simple_gfm

run-name: 308_simple_gfm

on:
  workflow_dispatch:
  pull_request:

permissions:
  pull-requests: write

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: time
        run: |
          echo "DATE=$(date +'%r')" >> $GITHUB_ENV

      - name: Adding markdown
        run: |
          echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY
          echo "   _(event **${{ github.event_name }}** / attempt **${{ github.run_attempt }}**)_"

      - name: more otuput
        run: |
          echo "$DATE"
          echo "**more output**" >> $GITHUB_STEP_SUMMARY
          echo " end "


      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        id: PR_comment
        with:
          message: |
             I am a bot.
             :heavy_check_mark: @ $(DATE)
             - item 1
             - item 2
             - run number: ${{github.run_number}} 
             - run id: ${{github.run_id}}
             - event: ** ${{github.event_name}} **
             - attempt #: **${{github.run_attempt}}**
             - actor: ${{github.actor}}
             - OS:  ${{runner.os}}

# prints to github console, not to the PR
      - name: check outputs
        run: |
          echo "id : ${{ steps.PR_comment.outputs.id }}"
          echo "body : ${{ steps.PR_comment.outputs.body }}"
          echo "html-url : ${{ steps.PR_comment.outputs.html-url }}"