name:  308_simple_gfm

run-name: 308_simple_gfm

on:
  workflow_dispatch:
  pull_request:


jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Adding markdown
        run: |
          echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY
          echo "   _(event **${{ github.event_name }}** / attempt **${{ github.run_attempt }}**)_"

      - name: more otuput
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**more output** >> $GITHUB_STEP_SUMMARY
