name:  310_gfm

run-name: 310_gfm

on:
  workflow_dispatch:
  pull_request:


jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Commit results
        if: ${{ 4 > 3 }}
        run: |
          echo "plain commit"
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - name: Commit
        if: ${{ 3 > 4 }}
        run: |
          echo "user = bot"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update" || echo "no changes; nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        id: PR_comment
        with:
          message: |
             I am a bot.
             :heavy_check_mark:
             _(event **${{ github.event_name }}** / attempt **${{ github.run_attempt }}**)_

      - name: check outputs
        run: |
          echo "id : ${{ steps.PR_comment.outputs.id }}"
          echo "body : ${{ steps.PR_comment.outputs.body }}"
          echo "html-url : ${{ steps.PR_comment.outputs.html-url }}"
