# This is a basic workflow to help you get started with Actions

name: 315 simple echo

on:
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      Greeting: Hello from gha!
    steps:
      - uses: actions/checkout@v4

#       Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: summary
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"

# in act, prints word yellow (not color)
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$action_state" # This will output 'yellow'

