name:  330_on_issue


run-name: 330_on_issue
# NOTES:
# $GITHUB_STEP_SUMMARY appears in details of run

on:
  issues:
     types: [opened, edited, closed, reopened, deleted]

jobs:
  job1:
    runs-on: ubuntu-latest
    if:  github.ref_name == 'dev'
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name:   set time
        run: sudo timedatectl set-timezone America/Los_Angeles

      - name: Check out repository
        uses: actions/checkout@v4

      - name: time
        run: |
          echo "DATE=$(date +'%r')" >> $GITHUB_ENV

      - name: output for summary (at end)
        run: |
          echo "$DATE" >> $GITHUB_STEP_SUMMARY
          echo '### Trigger was an issue' >> $GITHUB_STEP_SUMMARY
          echo "   _(event **${{ github.event_name }}** / attempt **${{ github.run_attempt }}**)_" >> $GITHUB_STEP_SUMMARY
          echo "more output" >> $GITHUB_STEP_SUMMARY
	  echo 
          echo " end "


      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        id: PR_comment
        with:
          message: |
             I am a bot.
             :heavy_check_mark: @ "$DATE"
             - item 1
             - item 2
             - run number: ${{github.run_number}} 
             - run id: ${{github.run_id}}
             - event: **${{github.event_name}}** 
             - attempt #: **${{github.run_attempt}}**
             - actor: ${{github.actor}}
             - OS:  ${{runner.os}}
             - action:  ${{github.action}}
             - github.ref_name:  ${{github.ref_name}}

# prints to github console, not to the PR
      - name: check outputs
        run: |
          echo "id : ${{ steps.PR_comment.outputs.id }}"
          echo "body : ${{ steps.PR_comment.outputs.body }}"
          echo "html-url : ${{ steps.PR_comment.outputs.html-url }}"