# Purpose:   Catch a change in certain files

# REF:  https://github.com/Ana06/get-changed-files
# FAILS on ACT, to test use 'act push -W....'
# RUNS ONLY ON GITHUB!

name: 01_changed_file

on:
  push:
  pull_request:

  #  branches: [ $default-branch ]
  #pull_request:
  #  branches: [ $default-branch ]

  # This action does not work on  workflow_dispatch
  # workflow_dispatch:

jobs:
  step1:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4

    - name: Run script
      run: |
        echo "Hello, world!"
        echo "Add other actions to build,"

## any yml, but NOT in .github
    - uses: Ana06/get-changed-files@v2.3.0
      with:
        filter: '*'

# for NOT !.github/*/*.yml 

    - id: files
      uses: Ana06/get-changed-files@v2.3.0
      with:
        format: 'csv'
        filter: '*'
    - run: |
        mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
        for added_modified_file in "${added_modified_files[@]}"; do
        echo "Do something with this ${added_modified_file}."
        done
 
 

