# WORKS
name:  500_upload_artifact

run-name: 500_upload_artifact

on:
  workflow_dispatch:

jobs:
  task1:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: echo
        run:  echo "This is workflow_dispatch"

  task2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: echo task
        run: echo "Task2: works on GITHUB, not act"

# WORKS in github
# uploads multiple files
# does not work in act

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: goodbye.sh
          path: '**/*'
# this path uploads everything in root directory of package, careful.

      - name: finish
        run:  echo "task2 finished"


  branch-name:
    runs-on:  ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Current branch names
        run: |
          echo "Current branch = ${{ steps.branch-names.outputs.current_branch }}"
        # Outputs: "main" the branch that triggered the push event.

      - name: Running on the default branch.
        if: steps.branch-names.outputs.is_default == 'true'
        run: |
          echo "Running on default: ${{ steps.branch-names.outputs.current_branch }}"
        # Outputs: "Running on default: main".

      - name: Running on the default branch (i.e non tag based branch).
        if: steps.branch-names.outputs.is_tag == 'false' && steps.branch-names.outputs.is_default == 'true'
        run: |
          echo "Running on branch: ${{ steps.branch-names.outputs.current_branch }}"
        # Outputs: "Running on branch: main".

      - name: Get Ref brach name
        run: |
          echo "${{ steps.branch-names.outputs.ref_branch }}"
        #  Outputs: "main"

      - name: Default branch name
        run: |
          echo "${{ steps.branch-names.outputs.default_branch }}"
        # Outputs: "main" the default branch.





