# 510_pr   F A I L S in act
name:  510 pr
on: pull_request

permissions:
  pull-requests: write

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world ! :wave:
          file-path: run.R 