name:  510 pr

on:
  pull_request:
    types:  [opened, reopened]
    branches: [dev]
  push:
    branches: [dev]

run-name: 510 pr  ${{ github.run_number }}, @${{ github.actor }}


jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: info
        run: |
          echo "pull-request"

      - name: debug
        if:  ${{always}}
        run: |
          echo "ref:   ${{github.ref}} \n  head_ref: ${{github_head_ref}}"
