
## GOAL:   trigger on pull_request,  limited by
##         - branch dev
##         - only this file


name:  510 pr

on:
  pull_request:
    types:  [opened, reopened]
    branches: [dev]
    paths:
      - '510_pull_request.yml'
  push:
    branches: [dev]
    paths:
      - '510_pull_request.yml'

run-name: 510 pr  ${{ github.run_number }}, @${{ github.actor }}


jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: info
        run: |
          echo "pull-request"

      - name: debug
        if:  ${{ always() }}
        run: |
          echo "ref:   ${{github.ref}} "
          echo "head_ref: ${{github.head_ref}}"
          echo "event name: ${{ github.event_name }}"
