name: 800 QC Check ✅

## REF:   qc.yaml from ELI, issue #26
## WORKS
on:
  workflow_dispatch:

jobs:
  qc-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

#      - name: Check out CDISC_pilot_replication repository
#        uses: actions/checkout@v4
#        with:
#          repository: RConsortium/submissions-pilot3-adam
#          sparse-checkout: 'submission/adam'
#          path: submissions-pilot3-adam

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr", "jsonlite", "quarto", "diffdf", "rmarkdown", "safetyData", "tibble", "stringr", "haven"), repos = "https://packagemanager.posit.co/cran/__linux__/noble/latest")'

      - name: Render Quarto document
        run: |
          quarto render README.Rmd  --to gfm --output README.md
          quarto render qcReport1.qmd
          echo "QUARTO"

#      - name: Run quarto
#        run: R -e 'quarto::quarto_render("")'

#      - name: Upload report artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: qcReport.html
#          path: qcReport.html
#
#      - name: PR comment with file
#        uses: thollander/actions-comment-pull-request@v3
#        with:
#          file-path: qc.Rmd