name: Test

on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:

run-name: Try ${{ github.run_number }}, @${{ github.actor }}

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: env

      - name: Print events.json
        run: cat "$GITHUB_EVENT_PATH"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: bash
#        run: |
#          # If there are any unstaged or untracked files in 'dist/', then the action wasn't packaged properly
#          if git diff --name-only | grep '^dist/' || git ls-files --other --exclude-standard | grep '^dist/'; then
#            echo "You didn't package the action properly before pushing to remote." \
#            echo "Always run 'yarn all' before staging a commit."
#            echo "Below are the modified files in 'dist/' after running 'yarn && rm -rf dist/ && yarn all':"
#            git diff --name-only | grep '^dist/'
#            git ls-files --other --exclude-standard | grep '^dist/'
#            exit 1
#          fi

      - name: git
          git ls-files | grep 'yml'