# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: setup_r_simple

on:
  workflow_dispatch:
    branches: main
  #push:
  #  branches: main

jobs:
  experiments:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

     # - name: Install packages
     #   uses: r-lib/actions/setup-r-dependencies@v2
     #   with:
     #     packages: |
	#    any::admiral
        #    #any::tidyverse 
        #    #any::googlesheets4

      - name: Check out repository
        uses: actions/checkout@v3

      - name: print 
        run: Rscript -e 'print(mtcars)'

      - name:  say hello 
      - run:  | 
          echo "From action yml:  HELLO"
      

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          #git add survey_data.rds
          #git commit -m 'Data updated' || echo "No changes to commit"
          #git push origin || echo "No changes to commit"


